service: codebase

#frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  my-function:
    handler: src/handler.hello
    layers:
      - arn:aws:lambda:us-east-1:855802708532:layer:test-mylayer:2
    events:
      - http:
          path: /hello
          method: get
          cors: true

layers:
  # A Lambda layer
  CelestePackage:
    path: layers
    name: CelestePackage
    compatibleRuntimes:
      - python3.9

custom:
  pythonRequirements:
    dockerizePip: true
